export CLICOLOR=1
export EDITOR="nvim"

alias glog1="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias vi="vi"
alias vim="nvim"
alias ll="ls -halt"

